
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model PhoneNumber
 * 
 */
export type PhoneNumber = Prisma.PhoneNumberModel
/**
 * Model Admin
 * 
 */
export type Admin = Prisma.AdminModel
/**
 * Model Student
 * 
 */
export type Student = Prisma.StudentModel
/**
 * Model Skill
 * 
 */
export type Skill = Prisma.SkillModel
/**
 * Model SkillOffered
 * 
 */
export type SkillOffered = Prisma.SkillOfferedModel
/**
 * Model SkillWanted
 * 
 */
export type SkillWanted = Prisma.SkillWantedModel
/**
 * Model Request
 * 
 */
export type Request = Prisma.RequestModel
/**
 * Model Favorite
 * 
 */
export type Favorite = Prisma.FavoriteModel
/**
 * Model Report
 * 
 */
export type Report = Prisma.ReportModel
/**
 * Model RefreshToken
 * 
 */
export type RefreshToken = Prisma.RefreshTokenModel
/**
 * Model Contact
 * 
 */
export type Contact = Prisma.ContactModel
