
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  STUDENT: 'STUDENT'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const Availability = {
  Morning: 'Morning',
  Afternoon: 'Afternoon',
  Evening: 'Evening'
} as const

export type Availability = (typeof Availability)[keyof typeof Availability]


export const ExperienceLevel = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  ADVANCED: 'ADVANCED',
  EXPERT: 'EXPERT'
} as const

export type ExperienceLevel = (typeof ExperienceLevel)[keyof typeof ExperienceLevel]


export const RequestStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
} as const

export type RequestStatus = (typeof RequestStatus)[keyof typeof RequestStatus]
