
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  PhoneNumber: 'PhoneNumber',
  Admin: 'Admin',
  Student: 'Student',
  Skill: 'Skill',
  SkillOffered: 'SkillOffered',
  SkillWanted: 'SkillWanted',
  Request: 'Request',
  Favorite: 'Favorite',
  Report: 'Report',
  RefreshToken: 'RefreshToken',
  Contact: 'Contact'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  user_ID: 'user_ID',
  fullName: 'fullName',
  email: 'email',
  password: 'password',
  city: 'city',
  country: 'country',
  bio: 'bio',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const PhoneNumberScalarFieldEnum = {
  phone_ID: 'phone_ID',
  number: 'number',
  user_ID: 'user_ID'
} as const

export type PhoneNumberScalarFieldEnum = (typeof PhoneNumberScalarFieldEnum)[keyof typeof PhoneNumberScalarFieldEnum]


export const AdminScalarFieldEnum = {
  admin_ID: 'admin_ID'
} as const

export type AdminScalarFieldEnum = (typeof AdminScalarFieldEnum)[keyof typeof AdminScalarFieldEnum]


export const StudentScalarFieldEnum = {
  student_ID: 'student_ID',
  experienceLevel: 'experienceLevel',
  availability: 'availability',
  isProfilePublic: 'isProfilePublic',
  skillsCompleted: 'skillsCompleted'
} as const

export type StudentScalarFieldEnum = (typeof StudentScalarFieldEnum)[keyof typeof StudentScalarFieldEnum]


export const SkillScalarFieldEnum = {
  skill_ID: 'skill_ID',
  name: 'name',
  category: 'category'
} as const

export type SkillScalarFieldEnum = (typeof SkillScalarFieldEnum)[keyof typeof SkillScalarFieldEnum]


export const SkillOfferedScalarFieldEnum = {
  skillOffered_ID: 'skillOffered_ID',
  student_ID: 'student_ID',
  skill_ID: 'skill_ID'
} as const

export type SkillOfferedScalarFieldEnum = (typeof SkillOfferedScalarFieldEnum)[keyof typeof SkillOfferedScalarFieldEnum]


export const SkillWantedScalarFieldEnum = {
  skillWanted_ID: 'skillWanted_ID',
  student_ID: 'student_ID',
  skill_ID: 'skill_ID'
} as const

export type SkillWantedScalarFieldEnum = (typeof SkillWantedScalarFieldEnum)[keyof typeof SkillWantedScalarFieldEnum]


export const RequestScalarFieldEnum = {
  request_ID: 'request_ID',
  sender_ID: 'sender_ID',
  receiver_ID: 'receiver_ID',
  requestedSkill_ID: 'requestedSkill_ID',
  offeredSkill_ID: 'offeredSkill_ID',
  status: 'status',
  createdAt: 'createdAt',
  completedAt: 'completedAt'
} as const

export type RequestScalarFieldEnum = (typeof RequestScalarFieldEnum)[keyof typeof RequestScalarFieldEnum]


export const FavoriteScalarFieldEnum = {
  favorite_ID: 'favorite_ID',
  student_ID: 'student_ID',
  favStudent_ID: 'favStudent_ID',
  createdAt: 'createdAt'
} as const

export type FavoriteScalarFieldEnum = (typeof FavoriteScalarFieldEnum)[keyof typeof FavoriteScalarFieldEnum]


export const ReportScalarFieldEnum = {
  report_ID: 'report_ID',
  reporter_ID: 'reporter_ID',
  reportedUser_ID: 'reportedUser_ID',
  admin_ID: 'admin_ID',
  reason: 'reason',
  adminNotes: 'adminNotes',
  createdAt: 'createdAt'
} as const

export type ReportScalarFieldEnum = (typeof ReportScalarFieldEnum)[keyof typeof ReportScalarFieldEnum]


export const RefreshTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  user_ID: 'user_ID',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type RefreshTokenScalarFieldEnum = (typeof RefreshTokenScalarFieldEnum)[keyof typeof RefreshTokenScalarFieldEnum]


export const ContactScalarFieldEnum = {
  contact_ID: 'contact_ID',
  name: 'name',
  email: 'email',
  message: 'message',
  createdAt: 'createdAt'
} as const

export type ContactScalarFieldEnum = (typeof ContactScalarFieldEnum)[keyof typeof ContactScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UserOrderByRelevanceFieldEnum = {
  user_ID: 'user_ID',
  fullName: 'fullName',
  email: 'email',
  password: 'password',
  city: 'city',
  country: 'country',
  bio: 'bio'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const PhoneNumberOrderByRelevanceFieldEnum = {
  number: 'number',
  user_ID: 'user_ID'
} as const

export type PhoneNumberOrderByRelevanceFieldEnum = (typeof PhoneNumberOrderByRelevanceFieldEnum)[keyof typeof PhoneNumberOrderByRelevanceFieldEnum]


export const AdminOrderByRelevanceFieldEnum = {
  admin_ID: 'admin_ID'
} as const

export type AdminOrderByRelevanceFieldEnum = (typeof AdminOrderByRelevanceFieldEnum)[keyof typeof AdminOrderByRelevanceFieldEnum]


export const StudentOrderByRelevanceFieldEnum = {
  student_ID: 'student_ID'
} as const

export type StudentOrderByRelevanceFieldEnum = (typeof StudentOrderByRelevanceFieldEnum)[keyof typeof StudentOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const SkillOrderByRelevanceFieldEnum = {
  skill_ID: 'skill_ID',
  name: 'name',
  category: 'category'
} as const

export type SkillOrderByRelevanceFieldEnum = (typeof SkillOrderByRelevanceFieldEnum)[keyof typeof SkillOrderByRelevanceFieldEnum]


export const SkillOfferedOrderByRelevanceFieldEnum = {
  skillOffered_ID: 'skillOffered_ID',
  student_ID: 'student_ID',
  skill_ID: 'skill_ID'
} as const

export type SkillOfferedOrderByRelevanceFieldEnum = (typeof SkillOfferedOrderByRelevanceFieldEnum)[keyof typeof SkillOfferedOrderByRelevanceFieldEnum]


export const SkillWantedOrderByRelevanceFieldEnum = {
  skillWanted_ID: 'skillWanted_ID',
  student_ID: 'student_ID',
  skill_ID: 'skill_ID'
} as const

export type SkillWantedOrderByRelevanceFieldEnum = (typeof SkillWantedOrderByRelevanceFieldEnum)[keyof typeof SkillWantedOrderByRelevanceFieldEnum]


export const RequestOrderByRelevanceFieldEnum = {
  request_ID: 'request_ID',
  sender_ID: 'sender_ID',
  receiver_ID: 'receiver_ID',
  requestedSkill_ID: 'requestedSkill_ID',
  offeredSkill_ID: 'offeredSkill_ID'
} as const

export type RequestOrderByRelevanceFieldEnum = (typeof RequestOrderByRelevanceFieldEnum)[keyof typeof RequestOrderByRelevanceFieldEnum]


export const FavoriteOrderByRelevanceFieldEnum = {
  favorite_ID: 'favorite_ID',
  student_ID: 'student_ID',
  favStudent_ID: 'favStudent_ID'
} as const

export type FavoriteOrderByRelevanceFieldEnum = (typeof FavoriteOrderByRelevanceFieldEnum)[keyof typeof FavoriteOrderByRelevanceFieldEnum]


export const ReportOrderByRelevanceFieldEnum = {
  reporter_ID: 'reporter_ID',
  reportedUser_ID: 'reportedUser_ID',
  admin_ID: 'admin_ID',
  reason: 'reason',
  adminNotes: 'adminNotes'
} as const

export type ReportOrderByRelevanceFieldEnum = (typeof ReportOrderByRelevanceFieldEnum)[keyof typeof ReportOrderByRelevanceFieldEnum]


export const RefreshTokenOrderByRelevanceFieldEnum = {
  id: 'id',
  token: 'token',
  user_ID: 'user_ID'
} as const

export type RefreshTokenOrderByRelevanceFieldEnum = (typeof RefreshTokenOrderByRelevanceFieldEnum)[keyof typeof RefreshTokenOrderByRelevanceFieldEnum]


export const ContactOrderByRelevanceFieldEnum = {
  name: 'name',
  email: 'email',
  message: 'message'
} as const

export type ContactOrderByRelevanceFieldEnum = (typeof ContactOrderByRelevanceFieldEnum)[keyof typeof ContactOrderByRelevanceFieldEnum]

