
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PhoneNumber` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PhoneNumber
 * 
 */
export type PhoneNumberModel = runtime.Types.Result.DefaultSelection<Prisma.$PhoneNumberPayload>

export type AggregatePhoneNumber = {
  _count: PhoneNumberCountAggregateOutputType | null
  _avg: PhoneNumberAvgAggregateOutputType | null
  _sum: PhoneNumberSumAggregateOutputType | null
  _min: PhoneNumberMinAggregateOutputType | null
  _max: PhoneNumberMaxAggregateOutputType | null
}

export type PhoneNumberAvgAggregateOutputType = {
  phone_ID: number | null
}

export type PhoneNumberSumAggregateOutputType = {
  phone_ID: number | null
}

export type PhoneNumberMinAggregateOutputType = {
  phone_ID: number | null
  number: string | null
  user_ID: string | null
}

export type PhoneNumberMaxAggregateOutputType = {
  phone_ID: number | null
  number: string | null
  user_ID: string | null
}

export type PhoneNumberCountAggregateOutputType = {
  phone_ID: number
  number: number
  user_ID: number
  _all: number
}


export type PhoneNumberAvgAggregateInputType = {
  phone_ID?: true
}

export type PhoneNumberSumAggregateInputType = {
  phone_ID?: true
}

export type PhoneNumberMinAggregateInputType = {
  phone_ID?: true
  number?: true
  user_ID?: true
}

export type PhoneNumberMaxAggregateInputType = {
  phone_ID?: true
  number?: true
  user_ID?: true
}

export type PhoneNumberCountAggregateInputType = {
  phone_ID?: true
  number?: true
  user_ID?: true
  _all?: true
}

export type PhoneNumberAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PhoneNumber to aggregate.
   */
  where?: Prisma.PhoneNumberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PhoneNumbers to fetch.
   */
  orderBy?: Prisma.PhoneNumberOrderByWithRelationInput | Prisma.PhoneNumberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PhoneNumberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PhoneNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PhoneNumbers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PhoneNumbers
  **/
  _count?: true | PhoneNumberCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PhoneNumberAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PhoneNumberSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PhoneNumberMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PhoneNumberMaxAggregateInputType
}

export type GetPhoneNumberAggregateType<T extends PhoneNumberAggregateArgs> = {
      [P in keyof T & keyof AggregatePhoneNumber]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePhoneNumber[P]>
    : Prisma.GetScalarType<T[P], AggregatePhoneNumber[P]>
}




export type PhoneNumberGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PhoneNumberWhereInput
  orderBy?: Prisma.PhoneNumberOrderByWithAggregationInput | Prisma.PhoneNumberOrderByWithAggregationInput[]
  by: Prisma.PhoneNumberScalarFieldEnum[] | Prisma.PhoneNumberScalarFieldEnum
  having?: Prisma.PhoneNumberScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PhoneNumberCountAggregateInputType | true
  _avg?: PhoneNumberAvgAggregateInputType
  _sum?: PhoneNumberSumAggregateInputType
  _min?: PhoneNumberMinAggregateInputType
  _max?: PhoneNumberMaxAggregateInputType
}

export type PhoneNumberGroupByOutputType = {
  phone_ID: number
  number: string
  user_ID: string
  _count: PhoneNumberCountAggregateOutputType | null
  _avg: PhoneNumberAvgAggregateOutputType | null
  _sum: PhoneNumberSumAggregateOutputType | null
  _min: PhoneNumberMinAggregateOutputType | null
  _max: PhoneNumberMaxAggregateOutputType | null
}

type GetPhoneNumberGroupByPayload<T extends PhoneNumberGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PhoneNumberGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PhoneNumberGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PhoneNumberGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PhoneNumberGroupByOutputType[P]>
      }
    >
  >



export type PhoneNumberWhereInput = {
  AND?: Prisma.PhoneNumberWhereInput | Prisma.PhoneNumberWhereInput[]
  OR?: Prisma.PhoneNumberWhereInput[]
  NOT?: Prisma.PhoneNumberWhereInput | Prisma.PhoneNumberWhereInput[]
  phone_ID?: Prisma.IntFilter<"PhoneNumber"> | number
  number?: Prisma.StringFilter<"PhoneNumber"> | string
  user_ID?: Prisma.StringFilter<"PhoneNumber"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PhoneNumberOrderByWithRelationInput = {
  phone_ID?: Prisma.SortOrder
  number?: Prisma.SortOrder
  user_ID?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.PhoneNumberOrderByRelevanceInput
}

export type PhoneNumberWhereUniqueInput = Prisma.AtLeast<{
  phone_ID?: number
  AND?: Prisma.PhoneNumberWhereInput | Prisma.PhoneNumberWhereInput[]
  OR?: Prisma.PhoneNumberWhereInput[]
  NOT?: Prisma.PhoneNumberWhereInput | Prisma.PhoneNumberWhereInput[]
  number?: Prisma.StringFilter<"PhoneNumber"> | string
  user_ID?: Prisma.StringFilter<"PhoneNumber"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "phone_ID">

export type PhoneNumberOrderByWithAggregationInput = {
  phone_ID?: Prisma.SortOrder
  number?: Prisma.SortOrder
  user_ID?: Prisma.SortOrder
  _count?: Prisma.PhoneNumberCountOrderByAggregateInput
  _avg?: Prisma.PhoneNumberAvgOrderByAggregateInput
  _max?: Prisma.PhoneNumberMaxOrderByAggregateInput
  _min?: Prisma.PhoneNumberMinOrderByAggregateInput
  _sum?: Prisma.PhoneNumberSumOrderByAggregateInput
}

export type PhoneNumberScalarWhereWithAggregatesInput = {
  AND?: Prisma.PhoneNumberScalarWhereWithAggregatesInput | Prisma.PhoneNumberScalarWhereWithAggregatesInput[]
  OR?: Prisma.PhoneNumberScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PhoneNumberScalarWhereWithAggregatesInput | Prisma.PhoneNumberScalarWhereWithAggregatesInput[]
  phone_ID?: Prisma.IntWithAggregatesFilter<"PhoneNumber"> | number
  number?: Prisma.StringWithAggregatesFilter<"PhoneNumber"> | string
  user_ID?: Prisma.StringWithAggregatesFilter<"PhoneNumber"> | string
}

export type PhoneNumberCreateInput = {
  number: string
  user: Prisma.UserCreateNestedOneWithoutPhoneNumberInput
}

export type PhoneNumberUncheckedCreateInput = {
  phone_ID?: number
  number: string
  user_ID: string
}

export type PhoneNumberUpdateInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutPhoneNumberNestedInput
}

export type PhoneNumberUncheckedUpdateInput = {
  phone_ID?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  user_ID?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PhoneNumberCreateManyInput = {
  phone_ID?: number
  number: string
  user_ID: string
}

export type PhoneNumberUpdateManyMutationInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PhoneNumberUncheckedUpdateManyInput = {
  phone_ID?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
  user_ID?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PhoneNumberListRelationFilter = {
  every?: Prisma.PhoneNumberWhereInput
  some?: Prisma.PhoneNumberWhereInput
  none?: Prisma.PhoneNumberWhereInput
}

export type PhoneNumberOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PhoneNumberOrderByRelevanceInput = {
  fields: Prisma.PhoneNumberOrderByRelevanceFieldEnum | Prisma.PhoneNumberOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PhoneNumberCountOrderByAggregateInput = {
  phone_ID?: Prisma.SortOrder
  number?: Prisma.SortOrder
  user_ID?: Prisma.SortOrder
}

export type PhoneNumberAvgOrderByAggregateInput = {
  phone_ID?: Prisma.SortOrder
}

export type PhoneNumberMaxOrderByAggregateInput = {
  phone_ID?: Prisma.SortOrder
  number?: Prisma.SortOrder
  user_ID?: Prisma.SortOrder
}

export type PhoneNumberMinOrderByAggregateInput = {
  phone_ID?: Prisma.SortOrder
  number?: Prisma.SortOrder
  user_ID?: Prisma.SortOrder
}

export type PhoneNumberSumOrderByAggregateInput = {
  phone_ID?: Prisma.SortOrder
}

export type PhoneNumberCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PhoneNumberCreateWithoutUserInput, Prisma.PhoneNumberUncheckedCreateWithoutUserInput> | Prisma.PhoneNumberCreateWithoutUserInput[] | Prisma.PhoneNumberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PhoneNumberCreateOrConnectWithoutUserInput | Prisma.PhoneNumberCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PhoneNumberCreateManyUserInputEnvelope
  connect?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
}

export type PhoneNumberUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PhoneNumberCreateWithoutUserInput, Prisma.PhoneNumberUncheckedCreateWithoutUserInput> | Prisma.PhoneNumberCreateWithoutUserInput[] | Prisma.PhoneNumberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PhoneNumberCreateOrConnectWithoutUserInput | Prisma.PhoneNumberCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PhoneNumberCreateManyUserInputEnvelope
  connect?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
}

export type PhoneNumberUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PhoneNumberCreateWithoutUserInput, Prisma.PhoneNumberUncheckedCreateWithoutUserInput> | Prisma.PhoneNumberCreateWithoutUserInput[] | Prisma.PhoneNumberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PhoneNumberCreateOrConnectWithoutUserInput | Prisma.PhoneNumberCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PhoneNumberUpsertWithWhereUniqueWithoutUserInput | Prisma.PhoneNumberUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PhoneNumberCreateManyUserInputEnvelope
  set?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  disconnect?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  delete?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  connect?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  update?: Prisma.PhoneNumberUpdateWithWhereUniqueWithoutUserInput | Prisma.PhoneNumberUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PhoneNumberUpdateManyWithWhereWithoutUserInput | Prisma.PhoneNumberUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PhoneNumberScalarWhereInput | Prisma.PhoneNumberScalarWhereInput[]
}

export type PhoneNumberUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PhoneNumberCreateWithoutUserInput, Prisma.PhoneNumberUncheckedCreateWithoutUserInput> | Prisma.PhoneNumberCreateWithoutUserInput[] | Prisma.PhoneNumberUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PhoneNumberCreateOrConnectWithoutUserInput | Prisma.PhoneNumberCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PhoneNumberUpsertWithWhereUniqueWithoutUserInput | Prisma.PhoneNumberUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PhoneNumberCreateManyUserInputEnvelope
  set?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  disconnect?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  delete?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  connect?: Prisma.PhoneNumberWhereUniqueInput | Prisma.PhoneNumberWhereUniqueInput[]
  update?: Prisma.PhoneNumberUpdateWithWhereUniqueWithoutUserInput | Prisma.PhoneNumberUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PhoneNumberUpdateManyWithWhereWithoutUserInput | Prisma.PhoneNumberUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PhoneNumberScalarWhereInput | Prisma.PhoneNumberScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PhoneNumberCreateWithoutUserInput = {
  number: string
}

export type PhoneNumberUncheckedCreateWithoutUserInput = {
  phone_ID?: number
  number: string
}

export type PhoneNumberCreateOrConnectWithoutUserInput = {
  where: Prisma.PhoneNumberWhereUniqueInput
  create: Prisma.XOR<Prisma.PhoneNumberCreateWithoutUserInput, Prisma.PhoneNumberUncheckedCreateWithoutUserInput>
}

export type PhoneNumberCreateManyUserInputEnvelope = {
  data: Prisma.PhoneNumberCreateManyUserInput | Prisma.PhoneNumberCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PhoneNumberUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PhoneNumberWhereUniqueInput
  update: Prisma.XOR<Prisma.PhoneNumberUpdateWithoutUserInput, Prisma.PhoneNumberUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PhoneNumberCreateWithoutUserInput, Prisma.PhoneNumberUncheckedCreateWithoutUserInput>
}

export type PhoneNumberUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PhoneNumberWhereUniqueInput
  data: Prisma.XOR<Prisma.PhoneNumberUpdateWithoutUserInput, Prisma.PhoneNumberUncheckedUpdateWithoutUserInput>
}

export type PhoneNumberUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PhoneNumberScalarWhereInput
  data: Prisma.XOR<Prisma.PhoneNumberUpdateManyMutationInput, Prisma.PhoneNumberUncheckedUpdateManyWithoutUserInput>
}

export type PhoneNumberScalarWhereInput = {
  AND?: Prisma.PhoneNumberScalarWhereInput | Prisma.PhoneNumberScalarWhereInput[]
  OR?: Prisma.PhoneNumberScalarWhereInput[]
  NOT?: Prisma.PhoneNumberScalarWhereInput | Prisma.PhoneNumberScalarWhereInput[]
  phone_ID?: Prisma.IntFilter<"PhoneNumber"> | number
  number?: Prisma.StringFilter<"PhoneNumber"> | string
  user_ID?: Prisma.StringFilter<"PhoneNumber"> | string
}

export type PhoneNumberCreateManyUserInput = {
  phone_ID?: number
  number: string
}

export type PhoneNumberUpdateWithoutUserInput = {
  number?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PhoneNumberUncheckedUpdateWithoutUserInput = {
  phone_ID?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PhoneNumberUncheckedUpdateManyWithoutUserInput = {
  phone_ID?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.StringFieldUpdateOperationsInput | string
}



export type PhoneNumberSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  phone_ID?: boolean
  number?: boolean
  user_ID?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["phoneNumber"]>



export type PhoneNumberSelectScalar = {
  phone_ID?: boolean
  number?: boolean
  user_ID?: boolean
}

export type PhoneNumberOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"phone_ID" | "number" | "user_ID", ExtArgs["result"]["phoneNumber"]>
export type PhoneNumberInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PhoneNumberPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PhoneNumber"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    phone_ID: number
    number: string
    user_ID: string
  }, ExtArgs["result"]["phoneNumber"]>
  composites: {}
}

export type PhoneNumberGetPayload<S extends boolean | null | undefined | PhoneNumberDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload, S>

export type PhoneNumberCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PhoneNumberFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PhoneNumberCountAggregateInputType | true
  }

export interface PhoneNumberDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PhoneNumber'], meta: { name: 'PhoneNumber' } }
  /**
   * Find zero or one PhoneNumber that matches the filter.
   * @param {PhoneNumberFindUniqueArgs} args - Arguments to find a PhoneNumber
   * @example
   * // Get one PhoneNumber
   * const phoneNumber = await prisma.phoneNumber.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PhoneNumberFindUniqueArgs>(args: Prisma.SelectSubset<T, PhoneNumberFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PhoneNumber that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PhoneNumberFindUniqueOrThrowArgs} args - Arguments to find a PhoneNumber
   * @example
   * // Get one PhoneNumber
   * const phoneNumber = await prisma.phoneNumber.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PhoneNumberFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PhoneNumberFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PhoneNumber that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PhoneNumberFindFirstArgs} args - Arguments to find a PhoneNumber
   * @example
   * // Get one PhoneNumber
   * const phoneNumber = await prisma.phoneNumber.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PhoneNumberFindFirstArgs>(args?: Prisma.SelectSubset<T, PhoneNumberFindFirstArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PhoneNumber that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PhoneNumberFindFirstOrThrowArgs} args - Arguments to find a PhoneNumber
   * @example
   * // Get one PhoneNumber
   * const phoneNumber = await prisma.phoneNumber.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PhoneNumberFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PhoneNumberFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PhoneNumbers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PhoneNumberFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PhoneNumbers
   * const phoneNumbers = await prisma.phoneNumber.findMany()
   * 
   * // Get first 10 PhoneNumbers
   * const phoneNumbers = await prisma.phoneNumber.findMany({ take: 10 })
   * 
   * // Only select the `phone_ID`
   * const phoneNumberWithPhone_IDOnly = await prisma.phoneNumber.findMany({ select: { phone_ID: true } })
   * 
   */
  findMany<T extends PhoneNumberFindManyArgs>(args?: Prisma.SelectSubset<T, PhoneNumberFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PhoneNumber.
   * @param {PhoneNumberCreateArgs} args - Arguments to create a PhoneNumber.
   * @example
   * // Create one PhoneNumber
   * const PhoneNumber = await prisma.phoneNumber.create({
   *   data: {
   *     // ... data to create a PhoneNumber
   *   }
   * })
   * 
   */
  create<T extends PhoneNumberCreateArgs>(args: Prisma.SelectSubset<T, PhoneNumberCreateArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PhoneNumbers.
   * @param {PhoneNumberCreateManyArgs} args - Arguments to create many PhoneNumbers.
   * @example
   * // Create many PhoneNumbers
   * const phoneNumber = await prisma.phoneNumber.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PhoneNumberCreateManyArgs>(args?: Prisma.SelectSubset<T, PhoneNumberCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PhoneNumber.
   * @param {PhoneNumberDeleteArgs} args - Arguments to delete one PhoneNumber.
   * @example
   * // Delete one PhoneNumber
   * const PhoneNumber = await prisma.phoneNumber.delete({
   *   where: {
   *     // ... filter to delete one PhoneNumber
   *   }
   * })
   * 
   */
  delete<T extends PhoneNumberDeleteArgs>(args: Prisma.SelectSubset<T, PhoneNumberDeleteArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PhoneNumber.
   * @param {PhoneNumberUpdateArgs} args - Arguments to update one PhoneNumber.
   * @example
   * // Update one PhoneNumber
   * const phoneNumber = await prisma.phoneNumber.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PhoneNumberUpdateArgs>(args: Prisma.SelectSubset<T, PhoneNumberUpdateArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PhoneNumbers.
   * @param {PhoneNumberDeleteManyArgs} args - Arguments to filter PhoneNumbers to delete.
   * @example
   * // Delete a few PhoneNumbers
   * const { count } = await prisma.phoneNumber.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PhoneNumberDeleteManyArgs>(args?: Prisma.SelectSubset<T, PhoneNumberDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PhoneNumbers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PhoneNumberUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PhoneNumbers
   * const phoneNumber = await prisma.phoneNumber.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PhoneNumberUpdateManyArgs>(args: Prisma.SelectSubset<T, PhoneNumberUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PhoneNumber.
   * @param {PhoneNumberUpsertArgs} args - Arguments to update or create a PhoneNumber.
   * @example
   * // Update or create a PhoneNumber
   * const phoneNumber = await prisma.phoneNumber.upsert({
   *   create: {
   *     // ... data to create a PhoneNumber
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PhoneNumber we want to update
   *   }
   * })
   */
  upsert<T extends PhoneNumberUpsertArgs>(args: Prisma.SelectSubset<T, PhoneNumberUpsertArgs<ExtArgs>>): Prisma.Prisma__PhoneNumberClient<runtime.Types.Result.GetResult<Prisma.$PhoneNumberPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PhoneNumbers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PhoneNumberCountArgs} args - Arguments to filter PhoneNumbers to count.
   * @example
   * // Count the number of PhoneNumbers
   * const count = await prisma.phoneNumber.count({
   *   where: {
   *     // ... the filter for the PhoneNumbers we want to count
   *   }
   * })
  **/
  count<T extends PhoneNumberCountArgs>(
    args?: Prisma.Subset<T, PhoneNumberCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PhoneNumberCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PhoneNumber.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PhoneNumberAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PhoneNumberAggregateArgs>(args: Prisma.Subset<T, PhoneNumberAggregateArgs>): Prisma.PrismaPromise<GetPhoneNumberAggregateType<T>>

  /**
   * Group by PhoneNumber.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PhoneNumberGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PhoneNumberGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PhoneNumberGroupByArgs['orderBy'] }
      : { orderBy?: PhoneNumberGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PhoneNumberGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPhoneNumberGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PhoneNumber model
 */
readonly fields: PhoneNumberFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PhoneNumber.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PhoneNumberClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PhoneNumber model
 */
export interface PhoneNumberFieldRefs {
  readonly phone_ID: Prisma.FieldRef<"PhoneNumber", 'Int'>
  readonly number: Prisma.FieldRef<"PhoneNumber", 'String'>
  readonly user_ID: Prisma.FieldRef<"PhoneNumber", 'String'>
}
    

// Custom InputTypes
/**
 * PhoneNumber findUnique
 */
export type PhoneNumberFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * Filter, which PhoneNumber to fetch.
   */
  where: Prisma.PhoneNumberWhereUniqueInput
}

/**
 * PhoneNumber findUniqueOrThrow
 */
export type PhoneNumberFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * Filter, which PhoneNumber to fetch.
   */
  where: Prisma.PhoneNumberWhereUniqueInput
}

/**
 * PhoneNumber findFirst
 */
export type PhoneNumberFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * Filter, which PhoneNumber to fetch.
   */
  where?: Prisma.PhoneNumberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PhoneNumbers to fetch.
   */
  orderBy?: Prisma.PhoneNumberOrderByWithRelationInput | Prisma.PhoneNumberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PhoneNumbers.
   */
  cursor?: Prisma.PhoneNumberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PhoneNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PhoneNumbers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PhoneNumbers.
   */
  distinct?: Prisma.PhoneNumberScalarFieldEnum | Prisma.PhoneNumberScalarFieldEnum[]
}

/**
 * PhoneNumber findFirstOrThrow
 */
export type PhoneNumberFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * Filter, which PhoneNumber to fetch.
   */
  where?: Prisma.PhoneNumberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PhoneNumbers to fetch.
   */
  orderBy?: Prisma.PhoneNumberOrderByWithRelationInput | Prisma.PhoneNumberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PhoneNumbers.
   */
  cursor?: Prisma.PhoneNumberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PhoneNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PhoneNumbers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PhoneNumbers.
   */
  distinct?: Prisma.PhoneNumberScalarFieldEnum | Prisma.PhoneNumberScalarFieldEnum[]
}

/**
 * PhoneNumber findMany
 */
export type PhoneNumberFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * Filter, which PhoneNumbers to fetch.
   */
  where?: Prisma.PhoneNumberWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PhoneNumbers to fetch.
   */
  orderBy?: Prisma.PhoneNumberOrderByWithRelationInput | Prisma.PhoneNumberOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PhoneNumbers.
   */
  cursor?: Prisma.PhoneNumberWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PhoneNumbers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PhoneNumbers.
   */
  skip?: number
  distinct?: Prisma.PhoneNumberScalarFieldEnum | Prisma.PhoneNumberScalarFieldEnum[]
}

/**
 * PhoneNumber create
 */
export type PhoneNumberCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * The data needed to create a PhoneNumber.
   */
  data: Prisma.XOR<Prisma.PhoneNumberCreateInput, Prisma.PhoneNumberUncheckedCreateInput>
}

/**
 * PhoneNumber createMany
 */
export type PhoneNumberCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PhoneNumbers.
   */
  data: Prisma.PhoneNumberCreateManyInput | Prisma.PhoneNumberCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PhoneNumber update
 */
export type PhoneNumberUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * The data needed to update a PhoneNumber.
   */
  data: Prisma.XOR<Prisma.PhoneNumberUpdateInput, Prisma.PhoneNumberUncheckedUpdateInput>
  /**
   * Choose, which PhoneNumber to update.
   */
  where: Prisma.PhoneNumberWhereUniqueInput
}

/**
 * PhoneNumber updateMany
 */
export type PhoneNumberUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PhoneNumbers.
   */
  data: Prisma.XOR<Prisma.PhoneNumberUpdateManyMutationInput, Prisma.PhoneNumberUncheckedUpdateManyInput>
  /**
   * Filter which PhoneNumbers to update
   */
  where?: Prisma.PhoneNumberWhereInput
  /**
   * Limit how many PhoneNumbers to update.
   */
  limit?: number
}

/**
 * PhoneNumber upsert
 */
export type PhoneNumberUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * The filter to search for the PhoneNumber to update in case it exists.
   */
  where: Prisma.PhoneNumberWhereUniqueInput
  /**
   * In case the PhoneNumber found by the `where` argument doesn't exist, create a new PhoneNumber with this data.
   */
  create: Prisma.XOR<Prisma.PhoneNumberCreateInput, Prisma.PhoneNumberUncheckedCreateInput>
  /**
   * In case the PhoneNumber was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PhoneNumberUpdateInput, Prisma.PhoneNumberUncheckedUpdateInput>
}

/**
 * PhoneNumber delete
 */
export type PhoneNumberDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
  /**
   * Filter which PhoneNumber to delete.
   */
  where: Prisma.PhoneNumberWhereUniqueInput
}

/**
 * PhoneNumber deleteMany
 */
export type PhoneNumberDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PhoneNumbers to delete
   */
  where?: Prisma.PhoneNumberWhereInput
  /**
   * Limit how many PhoneNumbers to delete.
   */
  limit?: number
}

/**
 * PhoneNumber without action
 */
export type PhoneNumberDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PhoneNumber
   */
  select?: Prisma.PhoneNumberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PhoneNumber
   */
  omit?: Prisma.PhoneNumberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PhoneNumberInclude<ExtArgs> | null
}
