
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SkillWanted` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SkillWanted
 * 
 */
export type SkillWantedModel = runtime.Types.Result.DefaultSelection<Prisma.$SkillWantedPayload>

export type AggregateSkillWanted = {
  _count: SkillWantedCountAggregateOutputType | null
  _min: SkillWantedMinAggregateOutputType | null
  _max: SkillWantedMaxAggregateOutputType | null
}

export type SkillWantedMinAggregateOutputType = {
  id: string | null
  studentId: string | null
  skillId: string | null
}

export type SkillWantedMaxAggregateOutputType = {
  id: string | null
  studentId: string | null
  skillId: string | null
}

export type SkillWantedCountAggregateOutputType = {
  id: number
  studentId: number
  skillId: number
  _all: number
}


export type SkillWantedMinAggregateInputType = {
  id?: true
  studentId?: true
  skillId?: true
}

export type SkillWantedMaxAggregateInputType = {
  id?: true
  studentId?: true
  skillId?: true
}

export type SkillWantedCountAggregateInputType = {
  id?: true
  studentId?: true
  skillId?: true
  _all?: true
}

export type SkillWantedAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkillWanted to aggregate.
   */
  where?: Prisma.SkillWantedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillWanteds to fetch.
   */
  orderBy?: Prisma.SkillWantedOrderByWithRelationInput | Prisma.SkillWantedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SkillWantedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillWanteds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillWanteds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SkillWanteds
  **/
  _count?: true | SkillWantedCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SkillWantedMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SkillWantedMaxAggregateInputType
}

export type GetSkillWantedAggregateType<T extends SkillWantedAggregateArgs> = {
      [P in keyof T & keyof AggregateSkillWanted]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSkillWanted[P]>
    : Prisma.GetScalarType<T[P], AggregateSkillWanted[P]>
}




export type SkillWantedGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SkillWantedWhereInput
  orderBy?: Prisma.SkillWantedOrderByWithAggregationInput | Prisma.SkillWantedOrderByWithAggregationInput[]
  by: Prisma.SkillWantedScalarFieldEnum[] | Prisma.SkillWantedScalarFieldEnum
  having?: Prisma.SkillWantedScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SkillWantedCountAggregateInputType | true
  _min?: SkillWantedMinAggregateInputType
  _max?: SkillWantedMaxAggregateInputType
}

export type SkillWantedGroupByOutputType = {
  id: string
  studentId: string
  skillId: string
  _count: SkillWantedCountAggregateOutputType | null
  _min: SkillWantedMinAggregateOutputType | null
  _max: SkillWantedMaxAggregateOutputType | null
}

type GetSkillWantedGroupByPayload<T extends SkillWantedGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SkillWantedGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SkillWantedGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SkillWantedGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SkillWantedGroupByOutputType[P]>
      }
    >
  >



export type SkillWantedWhereInput = {
  AND?: Prisma.SkillWantedWhereInput | Prisma.SkillWantedWhereInput[]
  OR?: Prisma.SkillWantedWhereInput[]
  NOT?: Prisma.SkillWantedWhereInput | Prisma.SkillWantedWhereInput[]
  id?: Prisma.StringFilter<"SkillWanted"> | string
  studentId?: Prisma.StringFilter<"SkillWanted"> | string
  skillId?: Prisma.StringFilter<"SkillWanted"> | string
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
  requests?: Prisma.RequestListRelationFilter
}

export type SkillWantedOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  student?: Prisma.StudentOrderByWithRelationInput
  skill?: Prisma.SkillOrderByWithRelationInput
  requests?: Prisma.RequestOrderByRelationAggregateInput
  _relevance?: Prisma.SkillWantedOrderByRelevanceInput
}

export type SkillWantedWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SkillWantedWhereInput | Prisma.SkillWantedWhereInput[]
  OR?: Prisma.SkillWantedWhereInput[]
  NOT?: Prisma.SkillWantedWhereInput | Prisma.SkillWantedWhereInput[]
  studentId?: Prisma.StringFilter<"SkillWanted"> | string
  skillId?: Prisma.StringFilter<"SkillWanted"> | string
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
  requests?: Prisma.RequestListRelationFilter
}, "id">

export type SkillWantedOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  _count?: Prisma.SkillWantedCountOrderByAggregateInput
  _max?: Prisma.SkillWantedMaxOrderByAggregateInput
  _min?: Prisma.SkillWantedMinOrderByAggregateInput
}

export type SkillWantedScalarWhereWithAggregatesInput = {
  AND?: Prisma.SkillWantedScalarWhereWithAggregatesInput | Prisma.SkillWantedScalarWhereWithAggregatesInput[]
  OR?: Prisma.SkillWantedScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SkillWantedScalarWhereWithAggregatesInput | Prisma.SkillWantedScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SkillWanted"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"SkillWanted"> | string
  skillId?: Prisma.StringWithAggregatesFilter<"SkillWanted"> | string
}

export type SkillWantedCreateInput = {
  id?: string
  student: Prisma.StudentCreateNestedOneWithoutSkillWantedInput
  skill: Prisma.SkillCreateNestedOneWithoutSkillWantedInput
  requests?: Prisma.RequestCreateNestedManyWithoutOfferedSkillInput
}

export type SkillWantedUncheckedCreateInput = {
  id?: string
  studentId: string
  skillId: string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutOfferedSkillInput
}

export type SkillWantedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  student?: Prisma.StudentUpdateOneRequiredWithoutSkillWantedNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutSkillWantedNestedInput
  requests?: Prisma.RequestUpdateManyWithoutOfferedSkillNestedInput
}

export type SkillWantedUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutOfferedSkillNestedInput
}

export type SkillWantedCreateManyInput = {
  id?: string
  studentId: string
  skillId: string
}

export type SkillWantedUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillWantedUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillWantedListRelationFilter = {
  every?: Prisma.SkillWantedWhereInput
  some?: Prisma.SkillWantedWhereInput
  none?: Prisma.SkillWantedWhereInput
}

export type SkillWantedOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SkillWantedOrderByRelevanceInput = {
  fields: Prisma.SkillWantedOrderByRelevanceFieldEnum | Prisma.SkillWantedOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type SkillWantedCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type SkillWantedMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type SkillWantedMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type SkillWantedScalarRelationFilter = {
  is?: Prisma.SkillWantedWhereInput
  isNot?: Prisma.SkillWantedWhereInput
}

export type SkillWantedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutStudentInput, Prisma.SkillWantedUncheckedCreateWithoutStudentInput> | Prisma.SkillWantedCreateWithoutStudentInput[] | Prisma.SkillWantedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutStudentInput | Prisma.SkillWantedCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.SkillWantedCreateManyStudentInputEnvelope
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
}

export type SkillWantedUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutStudentInput, Prisma.SkillWantedUncheckedCreateWithoutStudentInput> | Prisma.SkillWantedCreateWithoutStudentInput[] | Prisma.SkillWantedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutStudentInput | Prisma.SkillWantedCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.SkillWantedCreateManyStudentInputEnvelope
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
}

export type SkillWantedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutStudentInput, Prisma.SkillWantedUncheckedCreateWithoutStudentInput> | Prisma.SkillWantedCreateWithoutStudentInput[] | Prisma.SkillWantedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutStudentInput | Prisma.SkillWantedCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.SkillWantedUpsertWithWhereUniqueWithoutStudentInput | Prisma.SkillWantedUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.SkillWantedCreateManyStudentInputEnvelope
  set?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  disconnect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  delete?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  update?: Prisma.SkillWantedUpdateWithWhereUniqueWithoutStudentInput | Prisma.SkillWantedUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.SkillWantedUpdateManyWithWhereWithoutStudentInput | Prisma.SkillWantedUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.SkillWantedScalarWhereInput | Prisma.SkillWantedScalarWhereInput[]
}

export type SkillWantedUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutStudentInput, Prisma.SkillWantedUncheckedCreateWithoutStudentInput> | Prisma.SkillWantedCreateWithoutStudentInput[] | Prisma.SkillWantedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutStudentInput | Prisma.SkillWantedCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.SkillWantedUpsertWithWhereUniqueWithoutStudentInput | Prisma.SkillWantedUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.SkillWantedCreateManyStudentInputEnvelope
  set?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  disconnect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  delete?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  update?: Prisma.SkillWantedUpdateWithWhereUniqueWithoutStudentInput | Prisma.SkillWantedUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.SkillWantedUpdateManyWithWhereWithoutStudentInput | Prisma.SkillWantedUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.SkillWantedScalarWhereInput | Prisma.SkillWantedScalarWhereInput[]
}

export type SkillWantedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutSkillInput, Prisma.SkillWantedUncheckedCreateWithoutSkillInput> | Prisma.SkillWantedCreateWithoutSkillInput[] | Prisma.SkillWantedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutSkillInput | Prisma.SkillWantedCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.SkillWantedCreateManySkillInputEnvelope
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
}

export type SkillWantedUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutSkillInput, Prisma.SkillWantedUncheckedCreateWithoutSkillInput> | Prisma.SkillWantedCreateWithoutSkillInput[] | Prisma.SkillWantedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutSkillInput | Prisma.SkillWantedCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.SkillWantedCreateManySkillInputEnvelope
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
}

export type SkillWantedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutSkillInput, Prisma.SkillWantedUncheckedCreateWithoutSkillInput> | Prisma.SkillWantedCreateWithoutSkillInput[] | Prisma.SkillWantedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutSkillInput | Prisma.SkillWantedCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.SkillWantedUpsertWithWhereUniqueWithoutSkillInput | Prisma.SkillWantedUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.SkillWantedCreateManySkillInputEnvelope
  set?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  disconnect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  delete?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  update?: Prisma.SkillWantedUpdateWithWhereUniqueWithoutSkillInput | Prisma.SkillWantedUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.SkillWantedUpdateManyWithWhereWithoutSkillInput | Prisma.SkillWantedUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.SkillWantedScalarWhereInput | Prisma.SkillWantedScalarWhereInput[]
}

export type SkillWantedUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutSkillInput, Prisma.SkillWantedUncheckedCreateWithoutSkillInput> | Prisma.SkillWantedCreateWithoutSkillInput[] | Prisma.SkillWantedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutSkillInput | Prisma.SkillWantedCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.SkillWantedUpsertWithWhereUniqueWithoutSkillInput | Prisma.SkillWantedUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.SkillWantedCreateManySkillInputEnvelope
  set?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  disconnect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  delete?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  connect?: Prisma.SkillWantedWhereUniqueInput | Prisma.SkillWantedWhereUniqueInput[]
  update?: Prisma.SkillWantedUpdateWithWhereUniqueWithoutSkillInput | Prisma.SkillWantedUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.SkillWantedUpdateManyWithWhereWithoutSkillInput | Prisma.SkillWantedUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.SkillWantedScalarWhereInput | Prisma.SkillWantedScalarWhereInput[]
}

export type SkillWantedCreateNestedOneWithoutRequestsInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutRequestsInput, Prisma.SkillWantedUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutRequestsInput
  connect?: Prisma.SkillWantedWhereUniqueInput
}

export type SkillWantedUpdateOneRequiredWithoutRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.SkillWantedCreateWithoutRequestsInput, Prisma.SkillWantedUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.SkillWantedCreateOrConnectWithoutRequestsInput
  upsert?: Prisma.SkillWantedUpsertWithoutRequestsInput
  connect?: Prisma.SkillWantedWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SkillWantedUpdateToOneWithWhereWithoutRequestsInput, Prisma.SkillWantedUpdateWithoutRequestsInput>, Prisma.SkillWantedUncheckedUpdateWithoutRequestsInput>
}

export type SkillWantedCreateWithoutStudentInput = {
  id?: string
  skill: Prisma.SkillCreateNestedOneWithoutSkillWantedInput
  requests?: Prisma.RequestCreateNestedManyWithoutOfferedSkillInput
}

export type SkillWantedUncheckedCreateWithoutStudentInput = {
  id?: string
  skillId: string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutOfferedSkillInput
}

export type SkillWantedCreateOrConnectWithoutStudentInput = {
  where: Prisma.SkillWantedWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillWantedCreateWithoutStudentInput, Prisma.SkillWantedUncheckedCreateWithoutStudentInput>
}

export type SkillWantedCreateManyStudentInputEnvelope = {
  data: Prisma.SkillWantedCreateManyStudentInput | Prisma.SkillWantedCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type SkillWantedUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.SkillWantedWhereUniqueInput
  update: Prisma.XOR<Prisma.SkillWantedUpdateWithoutStudentInput, Prisma.SkillWantedUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.SkillWantedCreateWithoutStudentInput, Prisma.SkillWantedUncheckedCreateWithoutStudentInput>
}

export type SkillWantedUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.SkillWantedWhereUniqueInput
  data: Prisma.XOR<Prisma.SkillWantedUpdateWithoutStudentInput, Prisma.SkillWantedUncheckedUpdateWithoutStudentInput>
}

export type SkillWantedUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.SkillWantedScalarWhereInput
  data: Prisma.XOR<Prisma.SkillWantedUpdateManyMutationInput, Prisma.SkillWantedUncheckedUpdateManyWithoutStudentInput>
}

export type SkillWantedScalarWhereInput = {
  AND?: Prisma.SkillWantedScalarWhereInput | Prisma.SkillWantedScalarWhereInput[]
  OR?: Prisma.SkillWantedScalarWhereInput[]
  NOT?: Prisma.SkillWantedScalarWhereInput | Prisma.SkillWantedScalarWhereInput[]
  id?: Prisma.StringFilter<"SkillWanted"> | string
  studentId?: Prisma.StringFilter<"SkillWanted"> | string
  skillId?: Prisma.StringFilter<"SkillWanted"> | string
}

export type SkillWantedCreateWithoutSkillInput = {
  id?: string
  student: Prisma.StudentCreateNestedOneWithoutSkillWantedInput
  requests?: Prisma.RequestCreateNestedManyWithoutOfferedSkillInput
}

export type SkillWantedUncheckedCreateWithoutSkillInput = {
  id?: string
  studentId: string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutOfferedSkillInput
}

export type SkillWantedCreateOrConnectWithoutSkillInput = {
  where: Prisma.SkillWantedWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillWantedCreateWithoutSkillInput, Prisma.SkillWantedUncheckedCreateWithoutSkillInput>
}

export type SkillWantedCreateManySkillInputEnvelope = {
  data: Prisma.SkillWantedCreateManySkillInput | Prisma.SkillWantedCreateManySkillInput[]
  skipDuplicates?: boolean
}

export type SkillWantedUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.SkillWantedWhereUniqueInput
  update: Prisma.XOR<Prisma.SkillWantedUpdateWithoutSkillInput, Prisma.SkillWantedUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.SkillWantedCreateWithoutSkillInput, Prisma.SkillWantedUncheckedCreateWithoutSkillInput>
}

export type SkillWantedUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.SkillWantedWhereUniqueInput
  data: Prisma.XOR<Prisma.SkillWantedUpdateWithoutSkillInput, Prisma.SkillWantedUncheckedUpdateWithoutSkillInput>
}

export type SkillWantedUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.SkillWantedScalarWhereInput
  data: Prisma.XOR<Prisma.SkillWantedUpdateManyMutationInput, Prisma.SkillWantedUncheckedUpdateManyWithoutSkillInput>
}

export type SkillWantedCreateWithoutRequestsInput = {
  id?: string
  student: Prisma.StudentCreateNestedOneWithoutSkillWantedInput
  skill: Prisma.SkillCreateNestedOneWithoutSkillWantedInput
}

export type SkillWantedUncheckedCreateWithoutRequestsInput = {
  id?: string
  studentId: string
  skillId: string
}

export type SkillWantedCreateOrConnectWithoutRequestsInput = {
  where: Prisma.SkillWantedWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillWantedCreateWithoutRequestsInput, Prisma.SkillWantedUncheckedCreateWithoutRequestsInput>
}

export type SkillWantedUpsertWithoutRequestsInput = {
  update: Prisma.XOR<Prisma.SkillWantedUpdateWithoutRequestsInput, Prisma.SkillWantedUncheckedUpdateWithoutRequestsInput>
  create: Prisma.XOR<Prisma.SkillWantedCreateWithoutRequestsInput, Prisma.SkillWantedUncheckedCreateWithoutRequestsInput>
  where?: Prisma.SkillWantedWhereInput
}

export type SkillWantedUpdateToOneWithWhereWithoutRequestsInput = {
  where?: Prisma.SkillWantedWhereInput
  data: Prisma.XOR<Prisma.SkillWantedUpdateWithoutRequestsInput, Prisma.SkillWantedUncheckedUpdateWithoutRequestsInput>
}

export type SkillWantedUpdateWithoutRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  student?: Prisma.StudentUpdateOneRequiredWithoutSkillWantedNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutSkillWantedNestedInput
}

export type SkillWantedUncheckedUpdateWithoutRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillWantedCreateManyStudentInput = {
  id?: string
  skillId: string
}

export type SkillWantedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skill?: Prisma.SkillUpdateOneRequiredWithoutSkillWantedNestedInput
  requests?: Prisma.RequestUpdateManyWithoutOfferedSkillNestedInput
}

export type SkillWantedUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutOfferedSkillNestedInput
}

export type SkillWantedUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillWantedCreateManySkillInput = {
  id?: string
  studentId: string
}

export type SkillWantedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  student?: Prisma.StudentUpdateOneRequiredWithoutSkillWantedNestedInput
  requests?: Prisma.RequestUpdateManyWithoutOfferedSkillNestedInput
}

export type SkillWantedUncheckedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutOfferedSkillNestedInput
}

export type SkillWantedUncheckedUpdateManyWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type SkillWantedCountOutputType
 */

export type SkillWantedCountOutputType = {
  requests: number
}

export type SkillWantedCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requests?: boolean | SkillWantedCountOutputTypeCountRequestsArgs
}

/**
 * SkillWantedCountOutputType without action
 */
export type SkillWantedCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWantedCountOutputType
   */
  select?: Prisma.SkillWantedCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SkillWantedCountOutputType without action
 */
export type SkillWantedCountOutputTypeCountRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestWhereInput
}


export type SkillWantedSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  skillId?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  requests?: boolean | Prisma.SkillWanted$requestsArgs<ExtArgs>
  _count?: boolean | Prisma.SkillWantedCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["skillWanted"]>



export type SkillWantedSelectScalar = {
  id?: boolean
  studentId?: boolean
  skillId?: boolean
}

export type SkillWantedOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "studentId" | "skillId", ExtArgs["result"]["skillWanted"]>
export type SkillWantedInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  requests?: boolean | Prisma.SkillWanted$requestsArgs<ExtArgs>
  _count?: boolean | Prisma.SkillWantedCountOutputTypeDefaultArgs<ExtArgs>
}

export type $SkillWantedPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SkillWanted"
  objects: {
    student: Prisma.$StudentPayload<ExtArgs>
    skill: Prisma.$SkillPayload<ExtArgs>
    requests: Prisma.$RequestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    studentId: string
    skillId: string
  }, ExtArgs["result"]["skillWanted"]>
  composites: {}
}

export type SkillWantedGetPayload<S extends boolean | null | undefined | SkillWantedDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload, S>

export type SkillWantedCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SkillWantedFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SkillWantedCountAggregateInputType | true
  }

export interface SkillWantedDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SkillWanted'], meta: { name: 'SkillWanted' } }
  /**
   * Find zero or one SkillWanted that matches the filter.
   * @param {SkillWantedFindUniqueArgs} args - Arguments to find a SkillWanted
   * @example
   * // Get one SkillWanted
   * const skillWanted = await prisma.skillWanted.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SkillWantedFindUniqueArgs>(args: Prisma.SelectSubset<T, SkillWantedFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SkillWanted that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SkillWantedFindUniqueOrThrowArgs} args - Arguments to find a SkillWanted
   * @example
   * // Get one SkillWanted
   * const skillWanted = await prisma.skillWanted.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SkillWantedFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SkillWantedFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkillWanted that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillWantedFindFirstArgs} args - Arguments to find a SkillWanted
   * @example
   * // Get one SkillWanted
   * const skillWanted = await prisma.skillWanted.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SkillWantedFindFirstArgs>(args?: Prisma.SelectSubset<T, SkillWantedFindFirstArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkillWanted that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillWantedFindFirstOrThrowArgs} args - Arguments to find a SkillWanted
   * @example
   * // Get one SkillWanted
   * const skillWanted = await prisma.skillWanted.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SkillWantedFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SkillWantedFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SkillWanteds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillWantedFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SkillWanteds
   * const skillWanteds = await prisma.skillWanted.findMany()
   * 
   * // Get first 10 SkillWanteds
   * const skillWanteds = await prisma.skillWanted.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const skillWantedWithIdOnly = await prisma.skillWanted.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SkillWantedFindManyArgs>(args?: Prisma.SelectSubset<T, SkillWantedFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SkillWanted.
   * @param {SkillWantedCreateArgs} args - Arguments to create a SkillWanted.
   * @example
   * // Create one SkillWanted
   * const SkillWanted = await prisma.skillWanted.create({
   *   data: {
   *     // ... data to create a SkillWanted
   *   }
   * })
   * 
   */
  create<T extends SkillWantedCreateArgs>(args: Prisma.SelectSubset<T, SkillWantedCreateArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SkillWanteds.
   * @param {SkillWantedCreateManyArgs} args - Arguments to create many SkillWanteds.
   * @example
   * // Create many SkillWanteds
   * const skillWanted = await prisma.skillWanted.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SkillWantedCreateManyArgs>(args?: Prisma.SelectSubset<T, SkillWantedCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a SkillWanted.
   * @param {SkillWantedDeleteArgs} args - Arguments to delete one SkillWanted.
   * @example
   * // Delete one SkillWanted
   * const SkillWanted = await prisma.skillWanted.delete({
   *   where: {
   *     // ... filter to delete one SkillWanted
   *   }
   * })
   * 
   */
  delete<T extends SkillWantedDeleteArgs>(args: Prisma.SelectSubset<T, SkillWantedDeleteArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SkillWanted.
   * @param {SkillWantedUpdateArgs} args - Arguments to update one SkillWanted.
   * @example
   * // Update one SkillWanted
   * const skillWanted = await prisma.skillWanted.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SkillWantedUpdateArgs>(args: Prisma.SelectSubset<T, SkillWantedUpdateArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SkillWanteds.
   * @param {SkillWantedDeleteManyArgs} args - Arguments to filter SkillWanteds to delete.
   * @example
   * // Delete a few SkillWanteds
   * const { count } = await prisma.skillWanted.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SkillWantedDeleteManyArgs>(args?: Prisma.SelectSubset<T, SkillWantedDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SkillWanteds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillWantedUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SkillWanteds
   * const skillWanted = await prisma.skillWanted.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SkillWantedUpdateManyArgs>(args: Prisma.SelectSubset<T, SkillWantedUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one SkillWanted.
   * @param {SkillWantedUpsertArgs} args - Arguments to update or create a SkillWanted.
   * @example
   * // Update or create a SkillWanted
   * const skillWanted = await prisma.skillWanted.upsert({
   *   create: {
   *     // ... data to create a SkillWanted
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SkillWanted we want to update
   *   }
   * })
   */
  upsert<T extends SkillWantedUpsertArgs>(args: Prisma.SelectSubset<T, SkillWantedUpsertArgs<ExtArgs>>): Prisma.Prisma__SkillWantedClient<runtime.Types.Result.GetResult<Prisma.$SkillWantedPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SkillWanteds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillWantedCountArgs} args - Arguments to filter SkillWanteds to count.
   * @example
   * // Count the number of SkillWanteds
   * const count = await prisma.skillWanted.count({
   *   where: {
   *     // ... the filter for the SkillWanteds we want to count
   *   }
   * })
  **/
  count<T extends SkillWantedCountArgs>(
    args?: Prisma.Subset<T, SkillWantedCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SkillWantedCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SkillWanted.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillWantedAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SkillWantedAggregateArgs>(args: Prisma.Subset<T, SkillWantedAggregateArgs>): Prisma.PrismaPromise<GetSkillWantedAggregateType<T>>

  /**
   * Group by SkillWanted.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillWantedGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SkillWantedGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SkillWantedGroupByArgs['orderBy'] }
      : { orderBy?: SkillWantedGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SkillWantedGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSkillWantedGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SkillWanted model
 */
readonly fields: SkillWantedFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SkillWanted.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SkillWantedClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  student<T extends Prisma.StudentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  requests<T extends Prisma.SkillWanted$requestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillWanted$requestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SkillWanted model
 */
export interface SkillWantedFieldRefs {
  readonly id: Prisma.FieldRef<"SkillWanted", 'String'>
  readonly studentId: Prisma.FieldRef<"SkillWanted", 'String'>
  readonly skillId: Prisma.FieldRef<"SkillWanted", 'String'>
}
    

// Custom InputTypes
/**
 * SkillWanted findUnique
 */
export type SkillWantedFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * Filter, which SkillWanted to fetch.
   */
  where: Prisma.SkillWantedWhereUniqueInput
}

/**
 * SkillWanted findUniqueOrThrow
 */
export type SkillWantedFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * Filter, which SkillWanted to fetch.
   */
  where: Prisma.SkillWantedWhereUniqueInput
}

/**
 * SkillWanted findFirst
 */
export type SkillWantedFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * Filter, which SkillWanted to fetch.
   */
  where?: Prisma.SkillWantedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillWanteds to fetch.
   */
  orderBy?: Prisma.SkillWantedOrderByWithRelationInput | Prisma.SkillWantedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkillWanteds.
   */
  cursor?: Prisma.SkillWantedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillWanteds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillWanteds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkillWanteds.
   */
  distinct?: Prisma.SkillWantedScalarFieldEnum | Prisma.SkillWantedScalarFieldEnum[]
}

/**
 * SkillWanted findFirstOrThrow
 */
export type SkillWantedFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * Filter, which SkillWanted to fetch.
   */
  where?: Prisma.SkillWantedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillWanteds to fetch.
   */
  orderBy?: Prisma.SkillWantedOrderByWithRelationInput | Prisma.SkillWantedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkillWanteds.
   */
  cursor?: Prisma.SkillWantedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillWanteds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillWanteds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkillWanteds.
   */
  distinct?: Prisma.SkillWantedScalarFieldEnum | Prisma.SkillWantedScalarFieldEnum[]
}

/**
 * SkillWanted findMany
 */
export type SkillWantedFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * Filter, which SkillWanteds to fetch.
   */
  where?: Prisma.SkillWantedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillWanteds to fetch.
   */
  orderBy?: Prisma.SkillWantedOrderByWithRelationInput | Prisma.SkillWantedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SkillWanteds.
   */
  cursor?: Prisma.SkillWantedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillWanteds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillWanteds.
   */
  skip?: number
  distinct?: Prisma.SkillWantedScalarFieldEnum | Prisma.SkillWantedScalarFieldEnum[]
}

/**
 * SkillWanted create
 */
export type SkillWantedCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * The data needed to create a SkillWanted.
   */
  data: Prisma.XOR<Prisma.SkillWantedCreateInput, Prisma.SkillWantedUncheckedCreateInput>
}

/**
 * SkillWanted createMany
 */
export type SkillWantedCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SkillWanteds.
   */
  data: Prisma.SkillWantedCreateManyInput | Prisma.SkillWantedCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SkillWanted update
 */
export type SkillWantedUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * The data needed to update a SkillWanted.
   */
  data: Prisma.XOR<Prisma.SkillWantedUpdateInput, Prisma.SkillWantedUncheckedUpdateInput>
  /**
   * Choose, which SkillWanted to update.
   */
  where: Prisma.SkillWantedWhereUniqueInput
}

/**
 * SkillWanted updateMany
 */
export type SkillWantedUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SkillWanteds.
   */
  data: Prisma.XOR<Prisma.SkillWantedUpdateManyMutationInput, Prisma.SkillWantedUncheckedUpdateManyInput>
  /**
   * Filter which SkillWanteds to update
   */
  where?: Prisma.SkillWantedWhereInput
  /**
   * Limit how many SkillWanteds to update.
   */
  limit?: number
}

/**
 * SkillWanted upsert
 */
export type SkillWantedUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * The filter to search for the SkillWanted to update in case it exists.
   */
  where: Prisma.SkillWantedWhereUniqueInput
  /**
   * In case the SkillWanted found by the `where` argument doesn't exist, create a new SkillWanted with this data.
   */
  create: Prisma.XOR<Prisma.SkillWantedCreateInput, Prisma.SkillWantedUncheckedCreateInput>
  /**
   * In case the SkillWanted was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SkillWantedUpdateInput, Prisma.SkillWantedUncheckedUpdateInput>
}

/**
 * SkillWanted delete
 */
export type SkillWantedDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
  /**
   * Filter which SkillWanted to delete.
   */
  where: Prisma.SkillWantedWhereUniqueInput
}

/**
 * SkillWanted deleteMany
 */
export type SkillWantedDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkillWanteds to delete
   */
  where?: Prisma.SkillWantedWhereInput
  /**
   * Limit how many SkillWanteds to delete.
   */
  limit?: number
}

/**
 * SkillWanted.requests
 */
export type SkillWanted$requestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Request
   */
  select?: Prisma.RequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Request
   */
  omit?: Prisma.RequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestInclude<ExtArgs> | null
  where?: Prisma.RequestWhereInput
  orderBy?: Prisma.RequestOrderByWithRelationInput | Prisma.RequestOrderByWithRelationInput[]
  cursor?: Prisma.RequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RequestScalarFieldEnum | Prisma.RequestScalarFieldEnum[]
}

/**
 * SkillWanted without action
 */
export type SkillWantedDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillWanted
   */
  select?: Prisma.SkillWantedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillWanted
   */
  omit?: Prisma.SkillWantedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillWantedInclude<ExtArgs> | null
}
