
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SkillOffered` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SkillOffered
 * 
 */
export type SkillOfferedModel = runtime.Types.Result.DefaultSelection<Prisma.$SkillOfferedPayload>

export type AggregateSkillOffered = {
  _count: SkillOfferedCountAggregateOutputType | null
  _min: SkillOfferedMinAggregateOutputType | null
  _max: SkillOfferedMaxAggregateOutputType | null
}

export type SkillOfferedMinAggregateOutputType = {
  id: string | null
  studentId: string | null
  skillId: string | null
}

export type SkillOfferedMaxAggregateOutputType = {
  id: string | null
  studentId: string | null
  skillId: string | null
}

export type SkillOfferedCountAggregateOutputType = {
  id: number
  studentId: number
  skillId: number
  _all: number
}


export type SkillOfferedMinAggregateInputType = {
  id?: true
  studentId?: true
  skillId?: true
}

export type SkillOfferedMaxAggregateInputType = {
  id?: true
  studentId?: true
  skillId?: true
}

export type SkillOfferedCountAggregateInputType = {
  id?: true
  studentId?: true
  skillId?: true
  _all?: true
}

export type SkillOfferedAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkillOffered to aggregate.
   */
  where?: Prisma.SkillOfferedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillOffereds to fetch.
   */
  orderBy?: Prisma.SkillOfferedOrderByWithRelationInput | Prisma.SkillOfferedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SkillOfferedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillOffereds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillOffereds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SkillOffereds
  **/
  _count?: true | SkillOfferedCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SkillOfferedMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SkillOfferedMaxAggregateInputType
}

export type GetSkillOfferedAggregateType<T extends SkillOfferedAggregateArgs> = {
      [P in keyof T & keyof AggregateSkillOffered]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSkillOffered[P]>
    : Prisma.GetScalarType<T[P], AggregateSkillOffered[P]>
}




export type SkillOfferedGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SkillOfferedWhereInput
  orderBy?: Prisma.SkillOfferedOrderByWithAggregationInput | Prisma.SkillOfferedOrderByWithAggregationInput[]
  by: Prisma.SkillOfferedScalarFieldEnum[] | Prisma.SkillOfferedScalarFieldEnum
  having?: Prisma.SkillOfferedScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SkillOfferedCountAggregateInputType | true
  _min?: SkillOfferedMinAggregateInputType
  _max?: SkillOfferedMaxAggregateInputType
}

export type SkillOfferedGroupByOutputType = {
  id: string
  studentId: string
  skillId: string
  _count: SkillOfferedCountAggregateOutputType | null
  _min: SkillOfferedMinAggregateOutputType | null
  _max: SkillOfferedMaxAggregateOutputType | null
}

type GetSkillOfferedGroupByPayload<T extends SkillOfferedGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SkillOfferedGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SkillOfferedGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SkillOfferedGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SkillOfferedGroupByOutputType[P]>
      }
    >
  >



export type SkillOfferedWhereInput = {
  AND?: Prisma.SkillOfferedWhereInput | Prisma.SkillOfferedWhereInput[]
  OR?: Prisma.SkillOfferedWhereInput[]
  NOT?: Prisma.SkillOfferedWhereInput | Prisma.SkillOfferedWhereInput[]
  id?: Prisma.StringFilter<"SkillOffered"> | string
  studentId?: Prisma.StringFilter<"SkillOffered"> | string
  skillId?: Prisma.StringFilter<"SkillOffered"> | string
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
  requests?: Prisma.RequestListRelationFilter
}

export type SkillOfferedOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  student?: Prisma.StudentOrderByWithRelationInput
  skill?: Prisma.SkillOrderByWithRelationInput
  requests?: Prisma.RequestOrderByRelationAggregateInput
  _relevance?: Prisma.SkillOfferedOrderByRelevanceInput
}

export type SkillOfferedWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SkillOfferedWhereInput | Prisma.SkillOfferedWhereInput[]
  OR?: Prisma.SkillOfferedWhereInput[]
  NOT?: Prisma.SkillOfferedWhereInput | Prisma.SkillOfferedWhereInput[]
  studentId?: Prisma.StringFilter<"SkillOffered"> | string
  skillId?: Prisma.StringFilter<"SkillOffered"> | string
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
  requests?: Prisma.RequestListRelationFilter
}, "id">

export type SkillOfferedOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  _count?: Prisma.SkillOfferedCountOrderByAggregateInput
  _max?: Prisma.SkillOfferedMaxOrderByAggregateInput
  _min?: Prisma.SkillOfferedMinOrderByAggregateInput
}

export type SkillOfferedScalarWhereWithAggregatesInput = {
  AND?: Prisma.SkillOfferedScalarWhereWithAggregatesInput | Prisma.SkillOfferedScalarWhereWithAggregatesInput[]
  OR?: Prisma.SkillOfferedScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SkillOfferedScalarWhereWithAggregatesInput | Prisma.SkillOfferedScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SkillOffered"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"SkillOffered"> | string
  skillId?: Prisma.StringWithAggregatesFilter<"SkillOffered"> | string
}

export type SkillOfferedCreateInput = {
  id?: string
  student: Prisma.StudentCreateNestedOneWithoutSkillOfferedInput
  skill: Prisma.SkillCreateNestedOneWithoutSkillOfferedInput
  requests?: Prisma.RequestCreateNestedManyWithoutRequestedSkillInput
}

export type SkillOfferedUncheckedCreateInput = {
  id?: string
  studentId: string
  skillId: string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutRequestedSkillInput
}

export type SkillOfferedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  student?: Prisma.StudentUpdateOneRequiredWithoutSkillOfferedNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutSkillOfferedNestedInput
  requests?: Prisma.RequestUpdateManyWithoutRequestedSkillNestedInput
}

export type SkillOfferedUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutRequestedSkillNestedInput
}

export type SkillOfferedCreateManyInput = {
  id?: string
  studentId: string
  skillId: string
}

export type SkillOfferedUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillOfferedUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillOfferedListRelationFilter = {
  every?: Prisma.SkillOfferedWhereInput
  some?: Prisma.SkillOfferedWhereInput
  none?: Prisma.SkillOfferedWhereInput
}

export type SkillOfferedOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SkillOfferedOrderByRelevanceInput = {
  fields: Prisma.SkillOfferedOrderByRelevanceFieldEnum | Prisma.SkillOfferedOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type SkillOfferedCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type SkillOfferedMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type SkillOfferedMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
}

export type SkillOfferedScalarRelationFilter = {
  is?: Prisma.SkillOfferedWhereInput
  isNot?: Prisma.SkillOfferedWhereInput
}

export type SkillOfferedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutStudentInput, Prisma.SkillOfferedUncheckedCreateWithoutStudentInput> | Prisma.SkillOfferedCreateWithoutStudentInput[] | Prisma.SkillOfferedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutStudentInput | Prisma.SkillOfferedCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.SkillOfferedCreateManyStudentInputEnvelope
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
}

export type SkillOfferedUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutStudentInput, Prisma.SkillOfferedUncheckedCreateWithoutStudentInput> | Prisma.SkillOfferedCreateWithoutStudentInput[] | Prisma.SkillOfferedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutStudentInput | Prisma.SkillOfferedCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.SkillOfferedCreateManyStudentInputEnvelope
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
}

export type SkillOfferedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutStudentInput, Prisma.SkillOfferedUncheckedCreateWithoutStudentInput> | Prisma.SkillOfferedCreateWithoutStudentInput[] | Prisma.SkillOfferedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutStudentInput | Prisma.SkillOfferedCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.SkillOfferedUpsertWithWhereUniqueWithoutStudentInput | Prisma.SkillOfferedUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.SkillOfferedCreateManyStudentInputEnvelope
  set?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  disconnect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  delete?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  update?: Prisma.SkillOfferedUpdateWithWhereUniqueWithoutStudentInput | Prisma.SkillOfferedUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.SkillOfferedUpdateManyWithWhereWithoutStudentInput | Prisma.SkillOfferedUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.SkillOfferedScalarWhereInput | Prisma.SkillOfferedScalarWhereInput[]
}

export type SkillOfferedUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutStudentInput, Prisma.SkillOfferedUncheckedCreateWithoutStudentInput> | Prisma.SkillOfferedCreateWithoutStudentInput[] | Prisma.SkillOfferedUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutStudentInput | Prisma.SkillOfferedCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.SkillOfferedUpsertWithWhereUniqueWithoutStudentInput | Prisma.SkillOfferedUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.SkillOfferedCreateManyStudentInputEnvelope
  set?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  disconnect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  delete?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  update?: Prisma.SkillOfferedUpdateWithWhereUniqueWithoutStudentInput | Prisma.SkillOfferedUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.SkillOfferedUpdateManyWithWhereWithoutStudentInput | Prisma.SkillOfferedUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.SkillOfferedScalarWhereInput | Prisma.SkillOfferedScalarWhereInput[]
}

export type SkillOfferedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutSkillInput, Prisma.SkillOfferedUncheckedCreateWithoutSkillInput> | Prisma.SkillOfferedCreateWithoutSkillInput[] | Prisma.SkillOfferedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutSkillInput | Prisma.SkillOfferedCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.SkillOfferedCreateManySkillInputEnvelope
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
}

export type SkillOfferedUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutSkillInput, Prisma.SkillOfferedUncheckedCreateWithoutSkillInput> | Prisma.SkillOfferedCreateWithoutSkillInput[] | Prisma.SkillOfferedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutSkillInput | Prisma.SkillOfferedCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.SkillOfferedCreateManySkillInputEnvelope
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
}

export type SkillOfferedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutSkillInput, Prisma.SkillOfferedUncheckedCreateWithoutSkillInput> | Prisma.SkillOfferedCreateWithoutSkillInput[] | Prisma.SkillOfferedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutSkillInput | Prisma.SkillOfferedCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.SkillOfferedUpsertWithWhereUniqueWithoutSkillInput | Prisma.SkillOfferedUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.SkillOfferedCreateManySkillInputEnvelope
  set?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  disconnect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  delete?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  update?: Prisma.SkillOfferedUpdateWithWhereUniqueWithoutSkillInput | Prisma.SkillOfferedUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.SkillOfferedUpdateManyWithWhereWithoutSkillInput | Prisma.SkillOfferedUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.SkillOfferedScalarWhereInput | Prisma.SkillOfferedScalarWhereInput[]
}

export type SkillOfferedUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutSkillInput, Prisma.SkillOfferedUncheckedCreateWithoutSkillInput> | Prisma.SkillOfferedCreateWithoutSkillInput[] | Prisma.SkillOfferedUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutSkillInput | Prisma.SkillOfferedCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.SkillOfferedUpsertWithWhereUniqueWithoutSkillInput | Prisma.SkillOfferedUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.SkillOfferedCreateManySkillInputEnvelope
  set?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  disconnect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  delete?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  connect?: Prisma.SkillOfferedWhereUniqueInput | Prisma.SkillOfferedWhereUniqueInput[]
  update?: Prisma.SkillOfferedUpdateWithWhereUniqueWithoutSkillInput | Prisma.SkillOfferedUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.SkillOfferedUpdateManyWithWhereWithoutSkillInput | Prisma.SkillOfferedUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.SkillOfferedScalarWhereInput | Prisma.SkillOfferedScalarWhereInput[]
}

export type SkillOfferedCreateNestedOneWithoutRequestsInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutRequestsInput, Prisma.SkillOfferedUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutRequestsInput
  connect?: Prisma.SkillOfferedWhereUniqueInput
}

export type SkillOfferedUpdateOneRequiredWithoutRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.SkillOfferedCreateWithoutRequestsInput, Prisma.SkillOfferedUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.SkillOfferedCreateOrConnectWithoutRequestsInput
  upsert?: Prisma.SkillOfferedUpsertWithoutRequestsInput
  connect?: Prisma.SkillOfferedWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SkillOfferedUpdateToOneWithWhereWithoutRequestsInput, Prisma.SkillOfferedUpdateWithoutRequestsInput>, Prisma.SkillOfferedUncheckedUpdateWithoutRequestsInput>
}

export type SkillOfferedCreateWithoutStudentInput = {
  id?: string
  skill: Prisma.SkillCreateNestedOneWithoutSkillOfferedInput
  requests?: Prisma.RequestCreateNestedManyWithoutRequestedSkillInput
}

export type SkillOfferedUncheckedCreateWithoutStudentInput = {
  id?: string
  skillId: string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutRequestedSkillInput
}

export type SkillOfferedCreateOrConnectWithoutStudentInput = {
  where: Prisma.SkillOfferedWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillOfferedCreateWithoutStudentInput, Prisma.SkillOfferedUncheckedCreateWithoutStudentInput>
}

export type SkillOfferedCreateManyStudentInputEnvelope = {
  data: Prisma.SkillOfferedCreateManyStudentInput | Prisma.SkillOfferedCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type SkillOfferedUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.SkillOfferedWhereUniqueInput
  update: Prisma.XOR<Prisma.SkillOfferedUpdateWithoutStudentInput, Prisma.SkillOfferedUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.SkillOfferedCreateWithoutStudentInput, Prisma.SkillOfferedUncheckedCreateWithoutStudentInput>
}

export type SkillOfferedUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.SkillOfferedWhereUniqueInput
  data: Prisma.XOR<Prisma.SkillOfferedUpdateWithoutStudentInput, Prisma.SkillOfferedUncheckedUpdateWithoutStudentInput>
}

export type SkillOfferedUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.SkillOfferedScalarWhereInput
  data: Prisma.XOR<Prisma.SkillOfferedUpdateManyMutationInput, Prisma.SkillOfferedUncheckedUpdateManyWithoutStudentInput>
}

export type SkillOfferedScalarWhereInput = {
  AND?: Prisma.SkillOfferedScalarWhereInput | Prisma.SkillOfferedScalarWhereInput[]
  OR?: Prisma.SkillOfferedScalarWhereInput[]
  NOT?: Prisma.SkillOfferedScalarWhereInput | Prisma.SkillOfferedScalarWhereInput[]
  id?: Prisma.StringFilter<"SkillOffered"> | string
  studentId?: Prisma.StringFilter<"SkillOffered"> | string
  skillId?: Prisma.StringFilter<"SkillOffered"> | string
}

export type SkillOfferedCreateWithoutSkillInput = {
  id?: string
  student: Prisma.StudentCreateNestedOneWithoutSkillOfferedInput
  requests?: Prisma.RequestCreateNestedManyWithoutRequestedSkillInput
}

export type SkillOfferedUncheckedCreateWithoutSkillInput = {
  id?: string
  studentId: string
  requests?: Prisma.RequestUncheckedCreateNestedManyWithoutRequestedSkillInput
}

export type SkillOfferedCreateOrConnectWithoutSkillInput = {
  where: Prisma.SkillOfferedWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillOfferedCreateWithoutSkillInput, Prisma.SkillOfferedUncheckedCreateWithoutSkillInput>
}

export type SkillOfferedCreateManySkillInputEnvelope = {
  data: Prisma.SkillOfferedCreateManySkillInput | Prisma.SkillOfferedCreateManySkillInput[]
  skipDuplicates?: boolean
}

export type SkillOfferedUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.SkillOfferedWhereUniqueInput
  update: Prisma.XOR<Prisma.SkillOfferedUpdateWithoutSkillInput, Prisma.SkillOfferedUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.SkillOfferedCreateWithoutSkillInput, Prisma.SkillOfferedUncheckedCreateWithoutSkillInput>
}

export type SkillOfferedUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.SkillOfferedWhereUniqueInput
  data: Prisma.XOR<Prisma.SkillOfferedUpdateWithoutSkillInput, Prisma.SkillOfferedUncheckedUpdateWithoutSkillInput>
}

export type SkillOfferedUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.SkillOfferedScalarWhereInput
  data: Prisma.XOR<Prisma.SkillOfferedUpdateManyMutationInput, Prisma.SkillOfferedUncheckedUpdateManyWithoutSkillInput>
}

export type SkillOfferedCreateWithoutRequestsInput = {
  id?: string
  student: Prisma.StudentCreateNestedOneWithoutSkillOfferedInput
  skill: Prisma.SkillCreateNestedOneWithoutSkillOfferedInput
}

export type SkillOfferedUncheckedCreateWithoutRequestsInput = {
  id?: string
  studentId: string
  skillId: string
}

export type SkillOfferedCreateOrConnectWithoutRequestsInput = {
  where: Prisma.SkillOfferedWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillOfferedCreateWithoutRequestsInput, Prisma.SkillOfferedUncheckedCreateWithoutRequestsInput>
}

export type SkillOfferedUpsertWithoutRequestsInput = {
  update: Prisma.XOR<Prisma.SkillOfferedUpdateWithoutRequestsInput, Prisma.SkillOfferedUncheckedUpdateWithoutRequestsInput>
  create: Prisma.XOR<Prisma.SkillOfferedCreateWithoutRequestsInput, Prisma.SkillOfferedUncheckedCreateWithoutRequestsInput>
  where?: Prisma.SkillOfferedWhereInput
}

export type SkillOfferedUpdateToOneWithWhereWithoutRequestsInput = {
  where?: Prisma.SkillOfferedWhereInput
  data: Prisma.XOR<Prisma.SkillOfferedUpdateWithoutRequestsInput, Prisma.SkillOfferedUncheckedUpdateWithoutRequestsInput>
}

export type SkillOfferedUpdateWithoutRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  student?: Prisma.StudentUpdateOneRequiredWithoutSkillOfferedNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutSkillOfferedNestedInput
}

export type SkillOfferedUncheckedUpdateWithoutRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillOfferedCreateManyStudentInput = {
  id?: string
  skillId: string
}

export type SkillOfferedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skill?: Prisma.SkillUpdateOneRequiredWithoutSkillOfferedNestedInput
  requests?: Prisma.RequestUpdateManyWithoutRequestedSkillNestedInput
}

export type SkillOfferedUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutRequestedSkillNestedInput
}

export type SkillOfferedUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SkillOfferedCreateManySkillInput = {
  id?: string
  studentId: string
}

export type SkillOfferedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  student?: Prisma.StudentUpdateOneRequiredWithoutSkillOfferedNestedInput
  requests?: Prisma.RequestUpdateManyWithoutRequestedSkillNestedInput
}

export type SkillOfferedUncheckedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  requests?: Prisma.RequestUncheckedUpdateManyWithoutRequestedSkillNestedInput
}

export type SkillOfferedUncheckedUpdateManyWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type SkillOfferedCountOutputType
 */

export type SkillOfferedCountOutputType = {
  requests: number
}

export type SkillOfferedCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requests?: boolean | SkillOfferedCountOutputTypeCountRequestsArgs
}

/**
 * SkillOfferedCountOutputType without action
 */
export type SkillOfferedCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOfferedCountOutputType
   */
  select?: Prisma.SkillOfferedCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SkillOfferedCountOutputType without action
 */
export type SkillOfferedCountOutputTypeCountRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RequestWhereInput
}


export type SkillOfferedSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studentId?: boolean
  skillId?: boolean
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  requests?: boolean | Prisma.SkillOffered$requestsArgs<ExtArgs>
  _count?: boolean | Prisma.SkillOfferedCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["skillOffered"]>



export type SkillOfferedSelectScalar = {
  id?: boolean
  studentId?: boolean
  skillId?: boolean
}

export type SkillOfferedOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "studentId" | "skillId", ExtArgs["result"]["skillOffered"]>
export type SkillOfferedInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  requests?: boolean | Prisma.SkillOffered$requestsArgs<ExtArgs>
  _count?: boolean | Prisma.SkillOfferedCountOutputTypeDefaultArgs<ExtArgs>
}

export type $SkillOfferedPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SkillOffered"
  objects: {
    student: Prisma.$StudentPayload<ExtArgs>
    skill: Prisma.$SkillPayload<ExtArgs>
    requests: Prisma.$RequestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    studentId: string
    skillId: string
  }, ExtArgs["result"]["skillOffered"]>
  composites: {}
}

export type SkillOfferedGetPayload<S extends boolean | null | undefined | SkillOfferedDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload, S>

export type SkillOfferedCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SkillOfferedFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SkillOfferedCountAggregateInputType | true
  }

export interface SkillOfferedDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SkillOffered'], meta: { name: 'SkillOffered' } }
  /**
   * Find zero or one SkillOffered that matches the filter.
   * @param {SkillOfferedFindUniqueArgs} args - Arguments to find a SkillOffered
   * @example
   * // Get one SkillOffered
   * const skillOffered = await prisma.skillOffered.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SkillOfferedFindUniqueArgs>(args: Prisma.SelectSubset<T, SkillOfferedFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SkillOffered that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SkillOfferedFindUniqueOrThrowArgs} args - Arguments to find a SkillOffered
   * @example
   * // Get one SkillOffered
   * const skillOffered = await prisma.skillOffered.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SkillOfferedFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SkillOfferedFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkillOffered that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillOfferedFindFirstArgs} args - Arguments to find a SkillOffered
   * @example
   * // Get one SkillOffered
   * const skillOffered = await prisma.skillOffered.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SkillOfferedFindFirstArgs>(args?: Prisma.SelectSubset<T, SkillOfferedFindFirstArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkillOffered that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillOfferedFindFirstOrThrowArgs} args - Arguments to find a SkillOffered
   * @example
   * // Get one SkillOffered
   * const skillOffered = await prisma.skillOffered.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SkillOfferedFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SkillOfferedFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SkillOffereds that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillOfferedFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SkillOffereds
   * const skillOffereds = await prisma.skillOffered.findMany()
   * 
   * // Get first 10 SkillOffereds
   * const skillOffereds = await prisma.skillOffered.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const skillOfferedWithIdOnly = await prisma.skillOffered.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SkillOfferedFindManyArgs>(args?: Prisma.SelectSubset<T, SkillOfferedFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SkillOffered.
   * @param {SkillOfferedCreateArgs} args - Arguments to create a SkillOffered.
   * @example
   * // Create one SkillOffered
   * const SkillOffered = await prisma.skillOffered.create({
   *   data: {
   *     // ... data to create a SkillOffered
   *   }
   * })
   * 
   */
  create<T extends SkillOfferedCreateArgs>(args: Prisma.SelectSubset<T, SkillOfferedCreateArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SkillOffereds.
   * @param {SkillOfferedCreateManyArgs} args - Arguments to create many SkillOffereds.
   * @example
   * // Create many SkillOffereds
   * const skillOffered = await prisma.skillOffered.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SkillOfferedCreateManyArgs>(args?: Prisma.SelectSubset<T, SkillOfferedCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a SkillOffered.
   * @param {SkillOfferedDeleteArgs} args - Arguments to delete one SkillOffered.
   * @example
   * // Delete one SkillOffered
   * const SkillOffered = await prisma.skillOffered.delete({
   *   where: {
   *     // ... filter to delete one SkillOffered
   *   }
   * })
   * 
   */
  delete<T extends SkillOfferedDeleteArgs>(args: Prisma.SelectSubset<T, SkillOfferedDeleteArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SkillOffered.
   * @param {SkillOfferedUpdateArgs} args - Arguments to update one SkillOffered.
   * @example
   * // Update one SkillOffered
   * const skillOffered = await prisma.skillOffered.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SkillOfferedUpdateArgs>(args: Prisma.SelectSubset<T, SkillOfferedUpdateArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SkillOffereds.
   * @param {SkillOfferedDeleteManyArgs} args - Arguments to filter SkillOffereds to delete.
   * @example
   * // Delete a few SkillOffereds
   * const { count } = await prisma.skillOffered.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SkillOfferedDeleteManyArgs>(args?: Prisma.SelectSubset<T, SkillOfferedDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SkillOffereds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillOfferedUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SkillOffereds
   * const skillOffered = await prisma.skillOffered.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SkillOfferedUpdateManyArgs>(args: Prisma.SelectSubset<T, SkillOfferedUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one SkillOffered.
   * @param {SkillOfferedUpsertArgs} args - Arguments to update or create a SkillOffered.
   * @example
   * // Update or create a SkillOffered
   * const skillOffered = await prisma.skillOffered.upsert({
   *   create: {
   *     // ... data to create a SkillOffered
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SkillOffered we want to update
   *   }
   * })
   */
  upsert<T extends SkillOfferedUpsertArgs>(args: Prisma.SelectSubset<T, SkillOfferedUpsertArgs<ExtArgs>>): Prisma.Prisma__SkillOfferedClient<runtime.Types.Result.GetResult<Prisma.$SkillOfferedPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SkillOffereds.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillOfferedCountArgs} args - Arguments to filter SkillOffereds to count.
   * @example
   * // Count the number of SkillOffereds
   * const count = await prisma.skillOffered.count({
   *   where: {
   *     // ... the filter for the SkillOffereds we want to count
   *   }
   * })
  **/
  count<T extends SkillOfferedCountArgs>(
    args?: Prisma.Subset<T, SkillOfferedCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SkillOfferedCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SkillOffered.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillOfferedAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SkillOfferedAggregateArgs>(args: Prisma.Subset<T, SkillOfferedAggregateArgs>): Prisma.PrismaPromise<GetSkillOfferedAggregateType<T>>

  /**
   * Group by SkillOffered.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillOfferedGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SkillOfferedGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SkillOfferedGroupByArgs['orderBy'] }
      : { orderBy?: SkillOfferedGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SkillOfferedGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSkillOfferedGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SkillOffered model
 */
readonly fields: SkillOfferedFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SkillOffered.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SkillOfferedClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  student<T extends Prisma.StudentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  requests<T extends Prisma.SkillOffered$requestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillOffered$requestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SkillOffered model
 */
export interface SkillOfferedFieldRefs {
  readonly id: Prisma.FieldRef<"SkillOffered", 'String'>
  readonly studentId: Prisma.FieldRef<"SkillOffered", 'String'>
  readonly skillId: Prisma.FieldRef<"SkillOffered", 'String'>
}
    

// Custom InputTypes
/**
 * SkillOffered findUnique
 */
export type SkillOfferedFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * Filter, which SkillOffered to fetch.
   */
  where: Prisma.SkillOfferedWhereUniqueInput
}

/**
 * SkillOffered findUniqueOrThrow
 */
export type SkillOfferedFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * Filter, which SkillOffered to fetch.
   */
  where: Prisma.SkillOfferedWhereUniqueInput
}

/**
 * SkillOffered findFirst
 */
export type SkillOfferedFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * Filter, which SkillOffered to fetch.
   */
  where?: Prisma.SkillOfferedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillOffereds to fetch.
   */
  orderBy?: Prisma.SkillOfferedOrderByWithRelationInput | Prisma.SkillOfferedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkillOffereds.
   */
  cursor?: Prisma.SkillOfferedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillOffereds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillOffereds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkillOffereds.
   */
  distinct?: Prisma.SkillOfferedScalarFieldEnum | Prisma.SkillOfferedScalarFieldEnum[]
}

/**
 * SkillOffered findFirstOrThrow
 */
export type SkillOfferedFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * Filter, which SkillOffered to fetch.
   */
  where?: Prisma.SkillOfferedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillOffereds to fetch.
   */
  orderBy?: Prisma.SkillOfferedOrderByWithRelationInput | Prisma.SkillOfferedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkillOffereds.
   */
  cursor?: Prisma.SkillOfferedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillOffereds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillOffereds.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkillOffereds.
   */
  distinct?: Prisma.SkillOfferedScalarFieldEnum | Prisma.SkillOfferedScalarFieldEnum[]
}

/**
 * SkillOffered findMany
 */
export type SkillOfferedFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * Filter, which SkillOffereds to fetch.
   */
  where?: Prisma.SkillOfferedWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillOffereds to fetch.
   */
  orderBy?: Prisma.SkillOfferedOrderByWithRelationInput | Prisma.SkillOfferedOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SkillOffereds.
   */
  cursor?: Prisma.SkillOfferedWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillOffereds from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillOffereds.
   */
  skip?: number
  distinct?: Prisma.SkillOfferedScalarFieldEnum | Prisma.SkillOfferedScalarFieldEnum[]
}

/**
 * SkillOffered create
 */
export type SkillOfferedCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * The data needed to create a SkillOffered.
   */
  data: Prisma.XOR<Prisma.SkillOfferedCreateInput, Prisma.SkillOfferedUncheckedCreateInput>
}

/**
 * SkillOffered createMany
 */
export type SkillOfferedCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SkillOffereds.
   */
  data: Prisma.SkillOfferedCreateManyInput | Prisma.SkillOfferedCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SkillOffered update
 */
export type SkillOfferedUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * The data needed to update a SkillOffered.
   */
  data: Prisma.XOR<Prisma.SkillOfferedUpdateInput, Prisma.SkillOfferedUncheckedUpdateInput>
  /**
   * Choose, which SkillOffered to update.
   */
  where: Prisma.SkillOfferedWhereUniqueInput
}

/**
 * SkillOffered updateMany
 */
export type SkillOfferedUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SkillOffereds.
   */
  data: Prisma.XOR<Prisma.SkillOfferedUpdateManyMutationInput, Prisma.SkillOfferedUncheckedUpdateManyInput>
  /**
   * Filter which SkillOffereds to update
   */
  where?: Prisma.SkillOfferedWhereInput
  /**
   * Limit how many SkillOffereds to update.
   */
  limit?: number
}

/**
 * SkillOffered upsert
 */
export type SkillOfferedUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * The filter to search for the SkillOffered to update in case it exists.
   */
  where: Prisma.SkillOfferedWhereUniqueInput
  /**
   * In case the SkillOffered found by the `where` argument doesn't exist, create a new SkillOffered with this data.
   */
  create: Prisma.XOR<Prisma.SkillOfferedCreateInput, Prisma.SkillOfferedUncheckedCreateInput>
  /**
   * In case the SkillOffered was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SkillOfferedUpdateInput, Prisma.SkillOfferedUncheckedUpdateInput>
}

/**
 * SkillOffered delete
 */
export type SkillOfferedDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
  /**
   * Filter which SkillOffered to delete.
   */
  where: Prisma.SkillOfferedWhereUniqueInput
}

/**
 * SkillOffered deleteMany
 */
export type SkillOfferedDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkillOffereds to delete
   */
  where?: Prisma.SkillOfferedWhereInput
  /**
   * Limit how many SkillOffereds to delete.
   */
  limit?: number
}

/**
 * SkillOffered.requests
 */
export type SkillOffered$requestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Request
   */
  select?: Prisma.RequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Request
   */
  omit?: Prisma.RequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestInclude<ExtArgs> | null
  where?: Prisma.RequestWhereInput
  orderBy?: Prisma.RequestOrderByWithRelationInput | Prisma.RequestOrderByWithRelationInput[]
  cursor?: Prisma.RequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RequestScalarFieldEnum | Prisma.RequestScalarFieldEnum[]
}

/**
 * SkillOffered without action
 */
export type SkillOfferedDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillOffered
   */
  select?: Prisma.SkillOfferedSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillOffered
   */
  omit?: Prisma.SkillOfferedOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillOfferedInclude<ExtArgs> | null
}
